# 更新GitHub Actions部署脚本以支持Caddy
name: Deploy with Caddy SSL

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/your-project
          git pull origin main
          
          # 部署Next.js应用
          cd project2/nextjs_testing
          npm install
          npm run build
          pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
          
          # 部署FastAPI
          cd ../nextjs_fastapi
          source venv/bin/activate
          pip install -r requirements.txt
          systemctl restart fastapi
          
          # 重载Caddy配置（如果有更改）
          caddy reload --config /etc/caddy/Caddyfile